[package]
name = "mosse"
version = "0.1.0"
authors = ["Jurriaan Barkey Wolf <jjhbarkeywolf@gmail.com>"]

[dependencies]
image = "0.20.0"
rustfft = "2.1.0"
imageproc = "0.16.0"

# for font rendering on output/debug frames (same version as imageproc uses)
rusttype = "0.5"

[dev-dependencies]
time = "0.1.40"

[profile.release]
lto = true